package av

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"testing"
)

// Shared codec test vectors. The same file (testdata/vectors.json) is
// consumed by the JS twin's test suite (web/js/test/codecs.test.mjs); every
// expected byte sequence here is a contract both implementations must meet
// exactly. Regenerate with:  go test ./internal/av -run TestVectors -update
//
// []byte fields marshal as base64, which both Go and Node read natively.

var update = flag.Bool("update", false, "regenerate testdata/vectors.json")

const vectorsPath = "testdata/vectors.json"

type packbitsVector struct {
	Name   string `json:"name"`
	Raw    []byte `json:"raw"`
	Packed []byte `json:"packed"`
}

type ditherVector struct {
	Name           string `json:"name"`
	W              int    `json:"w"`
	H              int    `json:"h"`
	Gray           []byte `json:"gray"`
	BlueNoise      []byte `json:"blueNoise"`      // packed bitmap
	FloydSteinberg []byte `json:"floydSteinberg"` // packed bitmap
}

type videoVector struct {
	W           int          `json:"w"`
	H           int          `json:"h"`
	Source      uint8        `json:"source"`
	KeyInterval int          `json:"keyInterval"`
	Frames      []videoFrame `json:"frames"`
}

type videoFrame struct {
	Name   string `json:"name"`
	Bitmap []byte `json:"bitmap"`           // packed input frame
	Packet []byte `json:"packet,omitempty"` // nil = encoder skipped the frame
}

type audioVector struct {
	Source uint8        `json:"source"`
	Chunks []audioChunk `json:"chunks"`
}

type audioChunk struct {
	Name    string `json:"name"`
	PCM     []byte `json:"pcm"`     // int16 little-endian
	Packet  []byte `json:"packet"`  // complete media packet
	Decoded []byte `json:"decoded"` // int16 little-endian
}

type vectorFile struct {
	Comment  string           `json:"//"`
	PackBits []packbitsVector `json:"packbits"`
	Dither   []ditherVector   `json:"dither"`
	Video    videoVector      `json:"video"`
	Audio    audioVector      `json:"audio"`
}

func pcmToBytes(pcm []int16) []byte {
	out := make([]byte, len(pcm)*2)
	for i, s := range pcm {
		out[2*i] = byte(uint16(s))
		out[2*i+1] = byte(uint16(s) >> 8)
	}
	return out
}

func bytesToPCM(b []byte) []int16 {
	out := make([]int16, len(b)/2)
	for i := range out {
		out[i] = int16(uint16(b[2*i]) | uint16(b[2*i+1])<<8)
	}
	return out
}

// buildVectors produces the canonical vector set from this implementation.
func buildVectors() vectorFile {
	const w, h = 128, 96

	var vf vectorFile
	vf.Comment = "Shared codec test vectors; generated by `go test ./internal/av -run TestVectors -update`. Consumed byte-for-byte by both internal/av and web/js tests."

	// PackBits.
	rng := xorshift32(2)
	litRun := append(rng.bytes(40), bytes.Repeat([]byte{0xEE}, 200)...)
	for _, c := range []struct {
		name string
		raw  []byte
	}{
		{"empty", []byte{}},
		{"zeros-1536", make([]byte, 1536)},
		{"random-512", rng.bytes(512)},
		{"lit-then-run", litRun},
		{"pairs", bytes.Repeat([]byte{1, 1, 2, 2}, 60)},
	} {
		vf.PackBits = append(vf.PackBits, packbitsVector{Name: c.name, Raw: c.raw, Packed: PackBits(c.raw)})
	}

	// Dither.
	for _, c := range []struct {
		name string
		gray []byte
	}{
		{"gradient-box", gradientFrame(w, h, 30, 30)},
		{"noise", noiseFrame(w, h, 11)},
		{"mid-gray", flat(w, h, 128)},
	} {
		vf.Dither = append(vf.Dither, ditherVector{
			Name: c.name, W: w, H: h, Gray: c.gray,
			BlueNoise:      DitherBlueNoise(c.gray, w, h).Pix,
			FloydSteinberg: DitherFloydSteinberg(c.gray, w, h).Pix,
		})
	}

	// Video: a scripted sequence exercising every encoder rule —
	// first keyframe, motion deltas, static skips, cadence keyframe,
	// scene-cut keyframe, and recovery back to deltas.
	vv := videoVector{W: w, H: h, Source: 7, KeyInterval: 6}
	enc := &VideoEncoder{Source: 7, KeyInterval: 6}
	still := gradientFrame(w, h, 42, 30)
	script := []struct {
		name string
		gray []byte
	}{
		{"key-first", gradientFrame(w, h, 30, 30)},
		{"delta-move-1", gradientFrame(w, h, 34, 30)},
		{"delta-move-2", gradientFrame(w, h, 38, 30)},
		{"delta-move-3", still},
		{"skip-static-1", still},
		{"skip-static-2", still},
		{"key-cadence", still},
		{"key-scene-cut", noiseFrame(w, h, 21)},
		{"delta-after-cut", func() []byte { // noise with a small change
			g := noiseFrame(w, h, 21)
			for i := 0; i < 200; i++ {
				g[i+w*40] = 255
			}
			return g
		}()},
		{"delta-return", func() []byte {
			g := noiseFrame(w, h, 21)
			for i := 0; i < 400; i++ {
				g[i+w*40] = 255
			}
			return g
		}()},
	}
	for _, s := range script {
		bm := DitherBlueNoise(s.gray, w, h)
		vv.Frames = append(vv.Frames, videoFrame{Name: s.name, Bitmap: bm.Pix, Packet: enc.Encode(bm)})
	}
	vf.Video = vv

	// Audio: silence, a sine that carries quantizer state across chunks,
	// and noise.
	av := audioVector{Source: 3}
	aenc := &AudioEncoder{Source: 3}
	phase := 0.0
	var chunks []struct {
		name string
		pcm  []int16
	}
	chunks = append(chunks, struct {
		name string
		pcm  []int16
	}{"silence", make([]int16, ChunkSamples)})
	for i := 0; i < 3; i++ {
		var pcm []int16
		pcm, phase = sineChunk(440, 12000, phase, ChunkSamples)
		chunks = append(chunks, struct {
			name string
			pcm  []int16
		}{"sine-" + string(rune('a'+i)), pcm})
	}
	noisePCM := make([]int16, ChunkSamples)
	nrng := xorshift32(5)
	for i := range noisePCM {
		noisePCM[i] = int16(nrng.next())
	}
	chunks = append(chunks, struct {
		name string
		pcm  []int16
	}{"noise", noisePCM})

	for _, c := range chunks {
		raw, err := aenc.EncodeChunk(c.pcm)
		if err != nil {
			panic(err)
		}
		p, _ := ParsePacket(raw)
		dec, err := DecodeAudio(p)
		if err != nil {
			panic(err)
		}
		av.Chunks = append(av.Chunks, audioChunk{
			Name: c.name, PCM: pcmToBytes(c.pcm), Packet: raw, Decoded: pcmToBytes(dec),
		})
	}
	vf.Audio = av
	return vf
}

func TestVectors(t *testing.T) {
	if *update {
		vf := buildVectors()
		data, err := json.MarshalIndent(vf, "", " ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(vectorsPath, append(data, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", vectorsPath, len(data))
	}

	data, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("read vectors (run with -update to generate): %v", err)
	}
	var vf vectorFile
	if err := json.Unmarshal(data, &vf); err != nil {
		t.Fatal(err)
	}

	// PackBits: encode matches, decode round-trips.
	for _, v := range vf.PackBits {
		if got := PackBits(v.Raw); !bytes.Equal(got, v.Packed) {
			t.Errorf("packbits %q: encoded bytes differ from vector", v.Name)
		}
		got, err := UnpackBits(v.Packed, len(v.Raw))
		if err != nil || !bytes.Equal(got, v.Raw) {
			t.Errorf("packbits %q: decode: %v", v.Name, err)
		}
	}

	// Dither.
	for _, v := range vf.Dither {
		if got := DitherBlueNoise(v.Gray, v.W, v.H); !bytes.Equal(got.Pix, v.BlueNoise) {
			t.Errorf("dither %q: blue-noise output differs from vector", v.Name)
		}
		if got := DitherFloydSteinberg(v.Gray, v.W, v.H); !bytes.Equal(got.Pix, v.FloydSteinberg) {
			t.Errorf("dither %q: floyd-steinberg output differs from vector", v.Name)
		}
	}

	// Video: encoder reproduces each packet exactly; decoder reconstructs
	// each transmitted frame exactly.
	enc := &VideoEncoder{Source: vf.Video.Source, KeyInterval: vf.Video.KeyInterval}
	dec := &VideoDecoder{}
	for _, fr := range vf.Video.Frames {
		bm := &Bitmap{W: vf.Video.W, H: vf.Video.H, Pix: fr.Bitmap}
		got := enc.Encode(bm.Clone())
		if !bytes.Equal(got, fr.Packet) {
			t.Errorf("video %q: encoded packet differs from vector", fr.Name)
		}
		if fr.Packet == nil {
			continue
		}
		p, err := ParsePacket(fr.Packet)
		if err != nil {
			t.Fatalf("video %q: %v", fr.Name, err)
		}
		decoded, err := dec.Decode(p)
		if err != nil || decoded == nil {
			t.Fatalf("video %q: decode: (%v, %v)", fr.Name, decoded, err)
		}
		if !bytes.Equal(decoded.Pix, fr.Bitmap) {
			t.Errorf("video %q: decoded frame differs from source", fr.Name)
		}
	}

	// Audio: encoder reproduces packets; decoder reproduces PCM.
	aenc := &AudioEncoder{Source: vf.Audio.Source}
	for _, c := range vf.Audio.Chunks {
		raw, err := aenc.EncodeChunk(bytesToPCM(c.PCM))
		if err != nil {
			t.Fatalf("audio %q: %v", c.Name, err)
		}
		if !bytes.Equal(raw, c.Packet) {
			t.Errorf("audio %q: encoded packet differs from vector", c.Name)
		}
		p, _ := ParsePacket(c.Packet)
		dec, err := DecodeAudio(p)
		if err != nil {
			t.Fatalf("audio %q: decode: %v", c.Name, err)
		}
		if !bytes.Equal(pcmToBytes(dec), c.Decoded) {
			t.Errorf("audio %q: decoded PCM differs from vector", c.Name)
		}
	}

	// Sanity: the scripted video vector exercises every encoder rule.
	kinds := map[string]Kind{}
	for _, fr := range vf.Video.Frames {
		if fr.Packet == nil {
			continue
		}
		p, _ := ParsePacket(fr.Packet)
		kinds[fr.Name] = p.Kind
	}
	for name, want := range map[string]Kind{
		"key-first":     KindVideoKey,
		"delta-move-1":  KindVideoDelta,
		"key-cadence":   KindVideoKey,
		"key-scene-cut": KindVideoKey,
		"delta-return":  KindVideoDelta,
	} {
		if kinds[name] != want {
			t.Errorf("video vector %q: kind = 0x%02x, want 0x%02x", name, kinds[name], want)
		}
	}
	for _, name := range []string{"skip-static-1", "skip-static-2"} {
		for _, fr := range vf.Video.Frames {
			if fr.Name == name && fr.Packet != nil {
				t.Errorf("video vector %q: expected a skipped frame", name)
			}
		}
	}
}
