// Codec parity tests: validate the canonical JS codecs byte-for-byte against
// the shared vectors generated by the Go twin (internal/av/testdata/
// vectors.json — regenerate with `go test ./internal/av -run TestVectors
// -update`). Run with: node --test web/js/test/
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { packBits, unpackBits } from "../rle.js";
import { ditherBlueNoise, ditherFloydSteinberg } from "../dither.js";
import { VideoEncoder, VideoDecoder } from "../videocodec.js";
import { AudioEncoder, decodeAudio } from "../audiocodec.js";
import { parsePacket, KIND_VIDEO_KEY, KIND_VIDEO_DELTA } from "../packets.js";

const vectorsURL = new URL("../../../internal/av/testdata/vectors.json", import.meta.url);
const vectors = JSON.parse(readFileSync(vectorsURL, "utf8"));

function b64(s) {
  return s ? new Uint8Array(Buffer.from(s, "base64")) : new Uint8Array(0);
}

function pcm16(s) {
  const bytes = b64(s);
  const out = new Int16Array(bytes.length / 2);
  for (let i = 0; i < out.length; i++) {
    let v = bytes[2 * i] | (bytes[2 * i + 1] << 8);
    if (v & 0x8000) v -= 0x10000;
    out[i] = v;
  }
  return out;
}

test("packbits vectors", () => {
  for (const v of vectors.packbits) {
    const raw = b64(v.raw);
    const packed = b64(v.packed);
    assert.deepEqual(packBits(raw), packed, `${v.name}: encode`);
    assert.deepEqual(unpackBits(packed, raw.length), raw, `${v.name}: decode`);
  }
});

test("dither vectors", () => {
  for (const v of vectors.dither) {
    const gray = b64(v.gray);
    assert.deepEqual(
      ditherBlueNoise(gray, v.w, v.h), b64(v.blueNoise),
      `${v.name}: blue-noise output differs from Go`,
    );
    assert.deepEqual(
      ditherFloydSteinberg(gray, v.w, v.h), b64(v.floydSteinberg),
      `${v.name}: floyd-steinberg output differs from Go`,
    );
  }
});

test("video vectors: encoder matches Go byte-for-byte", () => {
  const vv = vectors.video;
  const enc = new VideoEncoder({ source: vv.source, keyInterval: vv.keyInterval });
  for (const fr of vv.frames) {
    const got = enc.encode(b64(fr.bitmap), vv.w, vv.h);
    if (!fr.packet) {
      assert.equal(got, null, `${fr.name}: expected a skipped frame`);
    } else {
      assert.deepEqual(got, b64(fr.packet), `${fr.name}: encoded packet differs from Go`);
    }
  }
});

test("video vectors: decoder reconstructs every transmitted frame", () => {
  const vv = vectors.video;
  const dec = new VideoDecoder();
  for (const fr of vv.frames) {
    if (!fr.packet) continue;
    const out = dec.decode(parsePacket(b64(fr.packet)));
    assert.ok(out, `${fr.name}: decoder returned null for an in-order packet`);
    assert.deepEqual(out.pix, b64(fr.bitmap), `${fr.name}: decoded frame differs from source`);
  }
});

test("video: drop freezes decoder until the next keyframe", () => {
  const w = 64, h = 32, stride = w >> 3;
  const enc = new VideoEncoder({ keyInterval: 5 });
  const dec = new VideoDecoder();

  // A noise base (incompressible keyframes) with a few bytes changing per
  // frame (cheap deltas), so the encoder genuinely picks deltas.
  const base = new Uint8Array(stride * h);
  let s = 0x2f6e2b1;
  for (let i = 0; i < base.length; i++) {
    s ^= s << 13; s ^= s >>> 17; s ^= s << 5; s |= 0;
    base[i] = s & 0xff;
  }

  const frames = [];
  const packets = [];
  for (let i = 0; i < 8; i++) {
    const pix = base.slice();
    for (let k = 0; k < 4; k++) pix[i * 16 + k] ^= 0xff; // small moving change
    frames.push(pix);
    const p = enc.encode(pix, w, h);
    assert.ok(p, `frame ${i} unexpectedly skipped`);
    packets.push(p);
    assert.equal(
      parsePacket(p).kind, i % 5 === 0 ? KIND_VIDEO_KEY : KIND_VIDEO_DELTA,
      `frame ${i}: unexpected kind`,
    );
  }

  assert.ok(dec.decode(parsePacket(packets[0])));
  assert.ok(dec.decode(parsePacket(packets[1])));
  // packets[2] lost in the relay: the next delta must not apply.
  assert.equal(dec.decode(parsePacket(packets[3])), null);
  assert.equal(dec.decode(parsePacket(packets[4])), null);
  // keyInterval=5 → packets[5] is the cadence keyframe: recovery.
  assert.equal(parsePacket(packets[5]).kind, KIND_VIDEO_KEY);
  const rec = dec.decode(parsePacket(packets[5]));
  assert.deepEqual(rec.pix, frames[5]);
  // Deltas apply cleanly again.
  assert.equal(parsePacket(packets[6]).kind, KIND_VIDEO_DELTA);
  assert.deepEqual(dec.decode(parsePacket(packets[6])).pix, frames[6]);
});

test("audio vectors: encoder and decoder match Go", () => {
  const av = vectors.audio;
  const enc = new AudioEncoder({ source: av.source });
  for (const c of av.chunks) {
    const packet = enc.encodeChunk(pcm16(c.pcm));
    assert.deepEqual(packet, b64(c.packet), `${c.name}: encoded packet differs from Go`);
    assert.deepEqual(
      decodeAudio(parsePacket(b64(c.packet))), pcm16(c.decoded),
      `${c.name}: decoded PCM differs from Go`,
    );
  }
});

test("audio: chunk decodes identically alone or in sequence", () => {
  const enc = new AudioEncoder({});
  const packets = [];
  for (let c = 0; c < 4; c++) {
    const pcm = new Int16Array(160);
    for (let i = 0; i < pcm.length; i++) {
      pcm[i] = Math.round(9000 * Math.sin((2 * Math.PI * 700 * (c * 160 + i)) / 8000));
    }
    packets.push(enc.encodeChunk(pcm));
  }
  const alone = decodeAudio(parsePacket(packets[2]));
  const again = decodeAudio(parsePacket(packets[2]));
  assert.deepEqual(alone, again);
});
